### ISSUE TITLE
Bug:  /root/.cache/torch/hub/requirements.txt not foun

### ISSUE THREAD

**Issue by ankhafizov** [EgShes/one_task_multiple_infras#5]
docker compose тритона падает с ошибкой requirements: /root/.cache/torch/hub/requirements.txt not found, check failed. Надо починить

**Comment by ankhafizov** [comment]
проблема использования poetry - сложно починить, не поработав раньше с поэтри)) явно что-то сломалось внутри yolo hub части

**Comment by EgShes** [comment]
Спасибо за репорт. Разберемся

**Comment by EgShes** [comment]
Можно только текст ошибки полный (с логами компоуза) и команду, которой запускали билд?

**Comment by ankhafizov** [comment]
так, ну если на винде, то запуск:
cd docker
docker-compose -f prod.yml up --build

ошибка:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/56340024/233935520-6adf6994-fb06-4781-8ca9-86589956767f.png">

**Comment by ankhafizov** [comment]
если линуха (убунту), то
DOCKER_BUILDKIT=1 docker-compose -f prod.yml up --build
а ошибка та же

**Comment by ankhafizov** [comment]
=> [internal] load build definition from DockerfileTriton                                                                                                     0.0s
 => => transferring dockerfile: 1.87kB                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                     1.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                0.0s
 => [internal] load build definition from DockerfileTriton                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/python:3.8                                                                                                  0.9s
 => [internal] load metadata for nvcr.io/nvidia/tritonserver:22.01-pyt-python-py3                                                                              2.2s
 => [requirements_maker  1/10] FROM docker.io/library/python:3.8@sha256:6aea47c16a4fe8a30f184060a2347caa24ea156b224041543fdc6b901dbec699                       0.0s
 => [base  1/10] FROM nvcr.io/nvidia/tritonserver:22.01-pyt-python-py3@sha256:f6c68991bc963da100f5457af1af5888e8bd668c6dca66968dff3269189b7f8f                 0.0s
 => [internal] load build context                                                                                                                              0.0s
 => => transferring context: 390.25kB                                                                                                                          0.0s
 => CACHED [requirements_maker  2/10] RUN --mount=type=cache,target=/root/.cache/pip     python3.8 -m venv /opt/poetry_venv     && /opt/poetry_venv/bin/pip i  0.0s
 => CACHED [requirements_maker  3/10] COPY ../inference_triton/pyproject.toml /app/inference_triton/pyproject.toml                                             0.0s
 => CACHED [requirements_maker  4/10] COPY ../inference_triton/poetry.lock /app/inference_triton/poetry.lock                                                   0.0s
 => CACHED [requirements_maker  5/10] COPY ../inference_triton/inference_triton/__init__.py /app/inference_triton/inference_triton/__init__.py                 0.0s
 => CACHED [requirements_maker  6/10] COPY ../nn/pyproject.toml /app/nn/pyproject.toml                                                                         0.0s
 => CACHED [requirements_maker  7/10] COPY ../nn/poetry.lock /app/nn/poetry.lock                                                                               0.0s
 => CACHED [requirements_maker  8/10] COPY ../nn/nn/__init__.py /app/nn/nn/__init__.py                                                                         0.0s
 => CACHED [requirements_maker  9/10] WORKDIR /app/inference_triton                                                                                            0.0s
 => CACHED [requirements_maker 10/10] RUN poetry export --format requirements.txt --without-hashes > /requirements.txt                                         0.0s
 => CACHED [base  2/10] COPY --from=requirements_maker /requirements.txt /requirements.txt                                                                     0.0s 
 => CACHED [base  3/10] COPY ../inference_triton/pyproject.toml /app/inference_triton/pyproject.toml                                                           0.0s 
 => CACHED [base  4/10] COPY ../inference_triton/poetry.lock /app/inference_triton/poetry.lock                                                                 0.0s 
 => CACHED [base  5/10] COPY ../inference_triton/inference_triton/__init__.py /app/inference_triton/inference_triton/__init__.py                               0.0s 
 => CACHED [base  6/10] COPY ../nn/pyproject.toml /app/nn/pyproject.toml                                                                                       0.0s 
 => CACHED [base  7/10] COPY ../nn/poetry.lock /app/nn/poetry.lock                                                                                             0.0s 
 => CACHED [base  8/10] COPY ../nn/nn/__init__.py /app/nn/nn/__init__.py                                                                                       0.0s 
 => CACHED [base  9/10] WORKDIR /app/inference_triton                                                                                                          0.0s 
 => CACHED [base 10/10] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r /requirements.txt     && pip install -e ../nn                        0.0s 
 => exporting to image                                                                                                                                         0.2s
 => => exporting layers                                                                                                                                        0.0s 
 => => writing image sha256:14b5b5f978a4484ed435e59c508b47c4a8c8520f4ba5392a199aa11c2c04beeb                                                                   0.0s 
 => => naming to docker.io/library/docker-triton                                                                                                               0.0s 
[+] Running 1/0
 - Container docker-triton-1  Created                                                                                                                          0.0s 
Attaching to docker-triton-1
docker-triton-1  | 
docker-triton-1  | =============================
docker-triton-1  | == Triton Inference Server ==
docker-triton-1  | =============================
docker-triton-1  |
docker-triton-1  | NVIDIA Release 22.01 (build 31237563)
docker-triton-1  |
docker-triton-1  | Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
docker-triton-1  |
docker-triton-1  | Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
docker-triton-1  |
docker-triton-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
docker-triton-1  | By pulling and using the container, you accept the terms and conditions of this license:
docker-triton-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
docker-triton-1  | 
docker-triton-1  | WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
docker-triton-1  |    Use Docker with NVIDIA Container Toolkit to start this container; see
docker-triton-1  |    https://github.com/NVIDIA/nvidia-docker.
docker-triton-1  |
docker-triton-1  | WARNING: [Torch-TensorRT] - Unable to read CUDA capable devices. Return status: 35
docker-triton-1  | I0424 08:00:58.894818 1 libtorch.cc:1227] TRITONBACKEND_Initialize: pytorch
docker-triton-1  | I0424 08:00:58.895071 1 libtorch.cc:1237] Triton TRITONBACKEND API version: 1.7
docker-triton-1  | I0424 08:00:58.895075 1 libtorch.cc:1243] 'pytorch' TRITONBACKEND API version: 1.7
docker-triton-1  | W0424 08:00:58.895482 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
docker-triton-1  | I0424 08:00:58.895911 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
docker-triton-1  | I0424 08:00:59.852148 1 model_repository_manager.cc:994] loading: stn:1
docker-triton-1  | I0424 08:00:59.969522 1 libtorch.cc:1276] TRITONBACKEND_ModelInitialize: stn (version 1)
docker-triton-1  | I0424 08:00:59.972272 1 libtorch.cc:253] Optimized execution is enabled for model instance 'stn'
docker-triton-1  | I0424 08:00:59.972303 1 libtorch.cc:271] Inference Mode is disabled for model instance 'stn'
docker-triton-1  | I0424 08:00:59.972308 1 libtorch.cc:346] NvFuser is not specified for model instance 'stn'
docker-triton-1  | I0424 08:00:59.972417 1 libtorch.cc:1317] TRITONBACKEND_ModelInstanceInitialize: stn (device 0)
docker-triton-1  | I0424 08:00:59.977828 1 model_repository_manager.cc:994] loading: plate_recognition:1
docker-triton-1  | I0424 08:01:00.037725 1 model_repository_manager.cc:1149] successfully loaded 'stn' version 1
docker-triton-1  | I0424 08:01:00.100838 1 python.cc:1897] TRITONBACKEND_ModelInstanceInitialize: plate_recognition (CPU device 0)
docker-triton-1  | I0424 08:01:00.104177 1 model_repository_manager.cc:994] loading: lprnet:1
docker-triton-1  | I0424 08:01:00.239829 1 model_repository_manager.cc:994] loading: yolo:1
docker-triton-1  | I0424 08:01:04.788224 1 libtorch.cc:1276] TRITONBACKEND_ModelInitialize: lprnet (version 1)
docker-triton-1  | I0424 08:01:04.788479 1 libtorch.cc:253] Optimized execution is enabled for model instance 'lprnet'
docker-triton-1  | I0424 08:01:04.788490 1 model_repository_manager.cc:1149] successfully loaded 'plate_recognition' version 1
docker-triton-1  | I0424 08:01:04.788494 1 libtorch.cc:271] Inference Mode is disabled for model instance 'lprnet'
docker-triton-1  | I0424 08:01:04.788502 1 libtorch.cc:346] NvFuser is not specified for model instance 'lprnet'
docker-triton-1  | I0424 08:01:04.788539 1 libtorch.cc:1317] TRITONBACKEND_ModelInstanceInitialize: lprnet (device 0)
docker-triton-1  | I0424 08:01:04.845833 1 model_repository_manager.cc:1149] successfully loaded 'lprnet' version 1
docker-triton-1  | I0424 08:01:04.845901 1 python.cc:1897] TRITONBACKEND_ModelInstanceInitialize: yolo (CPU device 0)
docker-triton-1  | Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
docker-triton-1  | YOLOv5 \U0001f680 2023-4-20 Python-3.8.10 torch-1.13.1+cu117 CPU
docker-triton-1  |
docker-triton-1  | Fusing layers... 
docker-triton-1  | Model summary: 378 layers, 35248920 parameters, 0 gradients
docker-triton-1  | Adding AutoShape...
docker-triton-1  | 0424 08:01:12.171219 74 pb_stub.cc:369] Failed to initialize Python stub: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
docker-triton-1  |
docker-triton-1  | At:
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py(249): _lazy_init
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(987): convert
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(664): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py(155): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py(647): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(989): to
docker-triton-1  |   /app/nn/nn/models/yolo.py(10): load_yolo
docker-triton-1  |   /app/inference_triton/inference_triton/model_repository/yolo/1/model.py(15): initialize
docker-triton-1  |
docker-triton-1  | E0424 08:01:12.171458 1 model_repository_manager.cc:1152] failed to load 'yolo' version 1: Internal: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
docker-triton-1  |
docker-triton-1  | At:
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py(249): _lazy_init
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(987): convert
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(664): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py(155): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply
docker-triton-1  |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py(647): _apply
docker-triton-1  |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(989): to
docker-triton-1  |   /app/nn/nn/models/yolo.py(10): load_yolo
docker-triton-1  |   /app/inference_triton/inference_triton/model_repository/yolo/1/model.py(15): initialize
docker-triton-1  |
docker-triton-1  | I0424 08:01:12.171555 1 server.cc:519]
docker-triton-1  | +------------------+------+
docker-triton-1  | | Repository Agent | Path |
docker-triton-1  | +------------------+------+
docker-triton-1  | +------------------+------+
docker-triton-1  |
docker-triton-1  | I0424 08:01:12.171596 1 server.cc:546]
docker-triton-1  | +---------+---------------------------------------------------------+--------+
docker-triton-1  | | Backend | Path                                                    | Config |
docker-triton-1  | +---------+---------------------------------------------------------+--------+
docker-triton-1  | | pytorch | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so | {}     |
docker-triton-1  | | python  | /opt/tritonserver/backends/python/libtriton_python.so   | {}     |
docker-triton-1  | +---------+---------------------------------------------------------+--------+
docker-triton-1  |
docker-triton-1  | I0424 08:01:12.171670 1 server.cc:589]
docker-triton-1  | +-------------------+---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  | | Model             | Version | Status                                                                                                           
                                                                          |
docker-triton-1  | +-------------------+---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  | | lprnet            | 1       | READY                                                                                                            
                                                                          |
docker-triton-1  | | plate_recognition | 1       | READY                                                                                                            
                                                                          |
docker-triton-1  | | stn               | 1       | READY                                                                                                            
                                                                          |
docker-triton-1  | | yolo              | 1       | UNAVAILABLE: Internal: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx |
docker-triton-1  | |                   |         |                                                                                                                  
                                                                          |
docker-triton-1  | |                   |         | At:                                                                                                              
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py(249): _lazy_init                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(987): convert                                
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(664): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py(155): _apply                                   
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(641): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py(647): _apply                                 
                                                                          |
docker-triton-1  | |                   |         |   /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(989): to                                     
                                                                          |
docker-triton-1  | |                   |         |   /app/nn/nn/models/yolo.py(10): load_yolo                                                                       
                                                                          |
docker-triton-1  | |                   |         |   /app/inference_triton/inference_triton/model_repository/yolo/1/model.py(15): initialize                        
                                                                          |
docker-triton-1  | +-------------------+---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  |
docker-triton-1  | I0424 08:01:12.171752 1 tritonserver.cc:1865]
docker-triton-1  | +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  | | Option                           | Value                                                                                                       
                                                                           |
docker-triton-1  | +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  | | server_id                        | triton                                                                                                      
                                                                           |
docker-triton-1  | | server_version                   | 2.18.0                                                                                                      
                                                                           |
docker-triton-1  | | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
docker-triton-1  | | model_repository_path[0]         | inference_triton/model_repository                                                                           
                                                                           |
docker-triton-1  | | model_control_mode               | MODE_NONE                                                                                                   
                                                                           |
docker-triton-1  | | strict_model_config              | 1                                                                                                           
                                                                           |
docker-triton-1  | | rate_limit                       | OFF                                                                                                         
                                                                           |
docker-triton-1  | | pinned_memory_pool_byte_size     | 268435456                                                                                                   
                                                                           |
docker-triton-1  | | response_cache_byte_size         | 0                                                                                                           
                                                                           |
docker-triton-1  | | min_supported_compute_capability | 6.0                                                                                                         
                                                                           |
docker-triton-1  | | strict_readiness                 | 1                                                                                                           
                                                                           |
docker-triton-1  | | exit_timeout                     | 30                                                                                                          
                                                                           |
docker-triton-1  | +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
docker-triton-1  |
docker-triton-1  | I0424 08:01:12.171765 1 server.cc:249] Waiting for in-flight requests to complete.
docker-triton-1  | I0424 08:01:12.171770 1 model_repository_manager.cc:1026] unloading: stn:1
docker-triton-1  | I0424 08:01:12.171825 1 model_repository_manager.cc:1026] unloading: plate_recognition:1
docker-triton-1  | I0424 08:01:12.171873 1 model_repository_manager.cc:1026] unloading: lprnet:1
docker-triton-1  | I0424 08:01:12.171919 1 server.cc:264] Timeout 30: Found 3 live models and 0 in-flight non-inference requests
docker-triton-1  | I0424 08:01:12.171933 1 libtorch.cc:1350] TRITONBACKEND_ModelInstanceFinalize: delete instance state
docker-triton-1  | I0424 08:01:12.172234 1 libtorch.cc:1350] TRITONBACKEND_ModelInstanceFinalize: delete instance state
docker-triton-1  | I0424 08:01:12.172271 1 libtorch.cc:1299] TRITONBACKEND_ModelFinalize: delete model state
docker-triton-1  | I0424 08:01:12.172289 1 model_repository_manager.cc:1132] successfully unloaded 'stn' version 1
docker-triton-1  | I0424 08:01:12.172617 1 libtorch.cc:1299] TRITONBACKEND_ModelFinalize: delete model state
docker-triton-1  | I0424 08:01:12.172726 1 model_repository_manager.cc:1132] successfully unloaded 'lprnet' version 1
docker-triton-1  | requirements: /root/.cache/torch/hub/requirements.txt not found, check failed.
docker-triton-1  | I0424 08:01:13.172073 1 server.cc:264] Timeout 29: Found 1 live models and 0 in-flight non-inference requests
docker-triton-1  | I0424 08:01:13.537935 1 model_repository_manager.cc:1132] successfully unloaded 'plate_recognition' version 1
docker-triton-1  | I0424 08:01:14.172482 1 server.cc:264] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
docker-triton-1  | error: creating server: Internal - failed to load all models
docker-triton-1 exited with code 1

**Comment by ankhafizov** [comment]
прочитав еще раз статью и докерфайл внимательнее, я понял, что проблема в маунте реквайрементс от поеьри. КМК здесь рил случился оверинжиниринг с поэтри, лучше перевести все в пип и ручками зафиксировать версии библитек, если необходимо. Поэтри сильно контринтуитивен для неопытных юзеров

**Comment by EgShes** [comment]
полагаю, что настоящая ошибка вот эта

docker-triton-1 | | yolo | 1 | UNAVAILABLE: Internal: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx |

Poetry отработал, потому что билд образа прошел.

**Comment by EgShes** [comment]
Видеокарта доступна в системе? Проверить можно так `docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`. Должен выдать [табличку](https://storage.googleapis.com/cdn.thenewstack.io/media/2018/03/689e2ec1-nvidia-smi.jpg) с доступной видеокартой

Если всё ок, то попробуйте явно указать (секция deploy) в компоузе, что даете доступ к гпу

```
services:

  triton:
    build:
      context: ../..
      dockerfile: inference_triton/docker/Dockerfiles/DockerfileTriton
    volumes:
      - ../../inference_triton:/app/inference_triton
      - ../../nn:/app/nn
    ports:
      - 8000:8000
    shm_size: '1gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

**Comment by ankhafizov** [comment]
да, так и есть)
На самом деле странная штука, почему тритон автоматически не заинференсил модели на цпу. Но здорово. Спасибо, ооочень помог!
